Exam_Result/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('teacher.urls')),
    path('student',include('student.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name='student'

urlpatterns=[
    path('',views.Search_student,name="search_student"),
    path('student_mark/<int:p>',views.MarkList,name='Mark'),
]

teacher/urls.py
from django.urls import path
from . import views

app_name='teacher'

urlpatterns=[
    path('',views.Home,name='home'),
]

student/models.py
from django.db import models

# Create your models here.

teacher/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Customuser(AbstractUser):
    phone = models.IntegerField(default=0)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.username

class Teacher(models.Model):
    Name=models.CharField(max_length=30)
    Tid=models.IntegerField(unique=True)
    Registerd=models.CharField(max_length=20,default='No')
    Registerd_on=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Name

class Students(models.Model):
    Name = models.CharField(max_length=30)
    Sid = models.IntegerField(unique=True)
    Registerd = models.CharField(max_length=20, default='No')
    Registerd_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Name

class Semester(models.Model):
    Semster_choices = (
        ('Semester 1', 'Semester 1'),
        ('Semester 2', 'Semester 2'),
        ('Semester 3', 'Semester 3'),
        ('Semester 4', 'Semester 4'),
        ('Semester 5', 'Semester 5'),
        ('Semester 6', 'Semester 6'),
    )

    name=models.CharField(max_length=30,choices=Semster_choices,unique=True)

    def __str__(self):
        return self.name


class Marks(models.Model):
    semester=models.ForeignKey(Semester,on_delete=models.CASCADE)
    student=models.ForeignKey(Students, on_delete=models.CASCADE)
    Language_1=models.IntegerField()
    Language_2=models.IntegerField()
    Maths=models.IntegerField()
    Physics=models.IntegerField()
    Chemistry=models.IntegerField()
    Statistics=models.IntegerField()
    Computer_Science=models.IntegerField()

    class Meta:
        unique_together = ('student','semester')

    def Total(self):
        return (self.Language_1 + self.Language_2 + self.Maths + self.Chemistry + self.Physics + self.Statistics + self.Computer_Science)

    def __str__(self):
        return f'{self.student.Name}_{self.semester.name}'

student/views.py
from django.shortcuts import render
from teacher.models import Marks,Students

# Create your views here.

def Search_student(request):

    if request.method=='POST':
        search_key=request.POST['search']

        if search_key !='':
            try:
                st=Students.objects.get(Sid=search_key)
                msg=''
            except:
                st=''
                msg='Enter Valid Student Id'
            return render(request, template_name='student.html',context={'msg':msg,'st':st})
        else:
            return render(request,template_name='student.html',context={'msg':'Enter Student Id'})


def MarkList(request,p):

    if request.method=='POST':
        student=Students.objects.get(Sid=p)
        sem=request.POST['Semester']
        if sem:  # Check if semester is provided
            try:
                marks = Marks.objects.get(semester=sem, student=student)
                return render(request, 'marklist.html', {'marks': marks})
            except Marks.DoesNotExist:
                # Handle the case where the marks are not found
                return render(request, 'marklist.html', {'error': 'Marks not found for the selected semester.'})
        else:
            return render(request, 'marklist.html', {'error': 'Please select a semester.'})
    return render(request,template_name='marklist.html')

teacher/views.py
from django.shortcuts import render
from .models import Marks,Semester
from django.db.models import F, ExpressionWrapper, IntegerField,Sum


# Create your views here.

def Home(request):
    total_expression = (
            F('Language_1') + F('Language_2') + F('Maths') +
            F('Physics') + F('Chemistry') + F('Statistics') +
            F('Computer_Science')
    )

    semester=Semester.objects.get(name='Semester 1')
    mark_queryset = Marks.objects.filter(semester=semester)

    annotated_marks = mark_queryset.annotate(
        total_marks=ExpressionWrapper(total_expression, output_field=IntegerField())
    )

    # Aggregate and sort by total_marks for each student and semester
    Top = (
        annotated_marks.values('student__id', 'student__Name', 'semester__id', 'semester__name')
            .annotate(total_marks=Sum('total_marks'))
            .order_by('-total_marks')
    )

    # Top 3 students in Maths
    maths = (
        annotated_marks.values('student__id', 'student__Name', 'semester__id', 'semester__name')
            .annotate(total_marks=Sum('Maths'))
            .order_by('-total_marks')
    )

    # Top 3 students in Physics
    physics = (
        annotated_marks.values('student__id', 'student__Name', 'semester__id', 'semester__name')
            .annotate(total_marks=Sum('Physics'))
            .order_by('-total_marks')
    )



    if request.method=='POST':
        sem=request.POST['Sem']
        # print(sem)
        semester=Semester.objects.get(id=sem)
        mark_queryset=Marks.objects.filter(semester=semester)

        annotated_marks = mark_queryset.annotate(
            total_marks=ExpressionWrapper(total_expression, output_field=IntegerField())
        )

        # Aggregate and sort by total_marks for each student and semester
        Top = (
            annotated_marks.values('student__id', 'student__Name', 'semester__id', 'semester__name')
                .annotate(total_marks=Sum('total_marks'))
                .order_by('-total_marks')
        )

        # Top 3 students in Maths
        maths = (
            annotated_marks.values('student__id', 'student__Name', 'semester__id', 'semester__name')
                .annotate(total_marks=Sum('Maths'))
                .order_by('-total_marks')
        )

        # Top 3 students in Physics
        physics = (
            annotated_marks.values('student__id', 'student__Name', 'semester__id', 'semester__name')
                .annotate(total_marks=Sum('Physics'))
                .order_by('-total_marks')
        )

        context = {
            'T3': Top,
            'Maths': maths,
            'Physics': physics,
            'semester':semester
        }

        return render(request, 'Home.html', context)

    context={'T3':Top,'Maths':maths,'Physics':physics,'semester':'Semester 1'}
    return render(request,template_name='Home.html',context=context)

templates/Home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container-fluid">
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}

        <div class="form-group" style="width:15%;">
            <label class="form-label fw-bold">Semester</label>
            <select class="form-control" name="Sem">
                <option value=1>Select semester</option>
                {% for i in sem %}
                <option value={{i.id}}>{{i}}</option>
                {% endfor %}
<!--                <option value="Semester 1">Semester 1</option>-->
<!--                <option value="Semester 2">Semester 2</option>-->
<!--                <option value="Semester 3">Semester 3</option>-->
<!--                <option value="Semester 4">Semester 4</option>-->
<!--                <option value="Semester 5">Semester 5</option>-->
<!--                <option value="Semester 6">Semester 6</option>-->

            </select>
            <div class="m-2 mb-4">
                <button type="submit" class="btn btn-primary"> Select </button>
            </div>
        </div>

    </form>
</div>


<div class="row container-fluid">
    <h2 class="text-center m-4">{{semester}}</h2>

    <div class="col-md-3 ms-4">
        <h4 class="fw-bold text-center">Maths Guru's</h4>
        <div>
            <table class="table">
                {% for i in Maths%}
                <tr>
                    <td>{{i.student__Name}}</td>
                    <td>{{i.total_marks}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-4 ms-4 fw-bold">
        <h3 class="fw-bold text-center">Top Students</h3>
        <div>

            <table class="table box-element">
                {% for i in T3 %}
                <tr class="border border-1">
                    <td>{{i.student__Name}}</td>
                    <td>{{i.total_marks}}</td>
                </tr>
                {% endfor %}
            </table>

        </div>
    </div>

    <div class="col-md-3 ms-4">
        <h4 class="fw-bold text-center">Physics Master's</h4>
        <div>
            <table class="table">
                {% for i in Physics %}
                <tr>
                    <td>{{i.student__Name}}</td>
                    <td>{{i.total_marks}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


<div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'teacher:home'%}">ABC School</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'teacher:home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
          </ul>
          <form class="d-flex" method="post" action="{% url 'student:search_student' %}">
              {%csrf_token%}
            <input class="form-control me-2" type="search" name="search" placeholder="Enter Student Id" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
</div>
{% block body %}
{% endblock %}

</body>
</html>

templates/marklist.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}

        <div class="form-group" style="width:15%;">
            <label class="form-label fw-bold">Semester</label>
            <select class="form-control" name="Semester">
                <option value=1>Select semester</option>
                {% for i in sem %}
                <option value={{i.id}}>{{i}}</option>
                {% endfor %}

            </select>
            <div class="m-2 mb-4">
                <button type="submit" class="btn btn-primary"> Select </button>
            </div>
        </div>

    </form>
    <div class="container-fluid">
        {% if marks%}
        <h4 class="text-primary">{{marks.semester}}</h4>

        <table class="table border border-2" style="width:40%;">
            <tr>
                <th>Language 1</th>
                <td>{{marks.Language_1}}</td>
            </tr>
            <tr>
                <th>Language 2</th>
                <td>{{marks.Language_2}}</td>
            </tr>
            <tr>
                <th>Chemistry</th>
                <td>{{marks.Chemistry}}</td>
            </tr>
            <tr>
                <th>Physics</th>
                <td>{{marks.Physics}}</td>
            </tr>
            <tr>
                <th>Maths</th>
                <td>{{marks.Maths}}</td>
            </tr>
            <tr>
                <th>Statistics</th>
                <td>{{marks.Statistics}}</td>
            </tr>
            <tr>
                <th>Computer</th>
                <td>{{marks.Computer_Science}}</td>
            </tr>
        </table>
        {% else %}
        <h3 class="text-warning">{{error}}</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/student.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            {% if st %}
            <table class="table border border-2" style="width:20%;">
                <tr>
                    <th class="border" style="width:30%;">Sid</th>
                    <td>{{st.Sid}}</td>
                </tr>
                <tr>
                    <th class="border" style="width:30%;">Name</th>
                    <td>{{st.Name}}</td>
                </tr>
            </table>
            {% else %}
            <h5>{{msg}}</h5>
            {% endif %}
        </div>
        {% if st %}
        <div class="col-md-8">
            <a class="btn btn-primary" href="{% url 'student:Mark' st.Sid %}">Get Mark List</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}